tasks:
  - init: git remote set-url origin git@github.com:gitpodcloudlabuser3/gitpodcloudlabuser3-test-1.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - kyntrack.rev-test-run